<?php


/**
 * ProcessWire Reusable Images
 *
 *
 * ProcessWire 3.x
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * @author Juraj Mydla
 * @version 0.0.1
 * @copyright Copyright (c) 2025 
 * @see https://github.com/justonestep/processwire-fieldtypeimageextra
 *
 */


namespace ProcessWire;

/**
 * Class FieldTypeImageReusable
 */

class FieldtypeImageReusable extends FieldtypeImage implements Module{


  /**
   * Retrieves module meta data
   * Implementation of the Module interface
   *
   * @return array
   * @see http://processwire.com/apigen/class-Module.html
   */
  public static function getModuleInfo() {
      return array(
        'title' => 'Reusable Images',
        'summary' => 'Field that stores one or more GIF, JPG, or PNG images with additional meta informations',
        'author' => 'Juraj Mydla',
        'version' => 001,
        'requires' => ['ProcessWire>=3.0.179', 'PHP>=7.4.0'],
        'autoload' => true,
        'installs' => 'ProcessReusableImages'
      );
  }

  /**
   * dbFields array // cache
   *
   */
  protected $dbFields = array();


  /**
   * init
   *
   */
  public function init() {
    parent::init();
    require_once __DIR__ . '/InputFieldImageReusable.php';
    $this->defaultInputfieldClass = 'InputfieldImageReusable';
  }

  /**
   * Return the DB schema used by this field's table
   *
   * @param Field $field
   */
  public function getDatabaseSchema(Field $field) {
    $schema = parent::getDatabaseSchema($field);
    $schema['uploaded_pages_id'] = 'int UNSIGNED NOT NULL';
    $schema['is_reference'] = 'tinyint(1) NOT NULL DEFAULT 0';
    $schema['keys']['uploaded_pages_id'] = 'index (uploaded_pages_id)';
    $schema['keys']['is_reference'] = 'index (is_reference)';
    return $schema;
  }

    public function saveFile(Page $page, Field $field, Pagefile $pagefile, array $columns = array()) {
      
      parent::saveFile($page, $field, $pagefile, $columns);

    }
}